### ISSUE TITLE
Nice Theif

### ISSUE THREAD

**Issue by Coolpyton** [Evolution-Development/PterodactylDash#1]
You have steal the code of The New client panel pterocp

**Comment by RianOP** [comment]
No, PterodactylDash is completely made by me.

**Comment by Coolpyton** [comment]
You have not make

**Comment by Coolpyton** [comment]
By your own

**Comment by Coolpyton** [comment]
You have steal the new pteroCp

**Comment by PadowYT2** [comment]
seems true xD
![https://cdn.padow.ru/NElW](https://cdn.padow.ru/NElW)

**Comment by SamCoLePug** [comment]
https://git.pterocp.com/PteroCP/PteroCP

**Comment by PadowYT2** [comment]
You have:
* Number routers
* .xml config (lmao)
* A lot of handlers

Which pterodash has:
* 1 mysql router
* .json config
* Only 2 handlers (and they are empty)
* pages/

Conclusion: There are 0 files copied, I'd like to hear the prove

**Comment by RianOP** [comment]
I didn't copy PteroCP, PteordactylDash is made entirely from scratch. Also, PteroCP likely has a lot of backends like Heliactyl (Wouldn't Recommend it). Stop trying to spam someone's GitHub when they made their own shit.
